spring.application.name=okazx

# JDBC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.test.database.replace=none

# Swagger UI
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true


# JWT secret key
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=${JWT_EXPIRATION_TIME}

# actuator
management.server.port=8080

management.endpoints.web.exposure.include=health,info,metrics,env,loggers
# management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=never


management.info.env.enabled=true
info.app.name=OkazX
info.app.version=1.0.0
info.app.description=E-commerce monolithic application built with Spring Boot

spring.config.import=optional:file:.env[.properties]